// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	dto "github.com/oyaguma3/eapaka-radius-server-poc/apps/vector-api/internal/dto"
	milenage "github.com/oyaguma3/eapaka-radius-server-poc/apps/vector-api/internal/milenage"
	store "github.com/oyaguma3/eapaka-radius-server-poc/apps/vector-api/internal/store"
	gomock "go.uber.org/mock/gomock"
)

// MockMilenageCalculator is a mock of MilenageCalculator interface.
type MockMilenageCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockMilenageCalculatorMockRecorder
	isgomock struct{}
}

// MockMilenageCalculatorMockRecorder is the mock recorder for MockMilenageCalculator.
type MockMilenageCalculatorMockRecorder struct {
	mock *MockMilenageCalculator
}

// NewMockMilenageCalculator creates a new mock instance.
func NewMockMilenageCalculator(ctrl *gomock.Controller) *MockMilenageCalculator {
	mock := &MockMilenageCalculator{ctrl: ctrl}
	mock.recorder = &MockMilenageCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMilenageCalculator) EXPECT() *MockMilenageCalculatorMockRecorder {
	return m.recorder
}

// GenerateVector mocks base method.
func (m *MockMilenageCalculator) GenerateVector(ki, opc, amf []byte, sqn uint64) (*milenage.Vector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateVector", ki, opc, amf, sqn)
	ret0, _ := ret[0].(*milenage.Vector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateVector indicates an expected call of GenerateVector.
func (mr *MockMilenageCalculatorMockRecorder) GenerateVector(ki, opc, amf, sqn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateVector", reflect.TypeOf((*MockMilenageCalculator)(nil).GenerateVector), ki, opc, amf, sqn)
}

// MockResyncProcessor is a mock of ResyncProcessor interface.
type MockResyncProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockResyncProcessorMockRecorder
	isgomock struct{}
}

// MockResyncProcessorMockRecorder is the mock recorder for MockResyncProcessor.
type MockResyncProcessorMockRecorder struct {
	mock *MockResyncProcessor
}

// NewMockResyncProcessor creates a new mock instance.
func NewMockResyncProcessor(ctrl *gomock.Controller) *MockResyncProcessor {
	mock := &MockResyncProcessor{ctrl: ctrl}
	mock.recorder = &MockResyncProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResyncProcessor) EXPECT() *MockResyncProcessorMockRecorder {
	return m.recorder
}

// ExtractSQN mocks base method.
func (m *MockResyncProcessor) ExtractSQN(ki, opc, rand, auts []byte) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractSQN", ki, opc, rand, auts)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractSQN indicates an expected call of ExtractSQN.
func (mr *MockResyncProcessorMockRecorder) ExtractSQN(ki, opc, rand, auts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractSQN", reflect.TypeOf((*MockResyncProcessor)(nil).ExtractSQN), ki, opc, rand, auts)
}

// MockSQNManager is a mock of SQNManager interface.
type MockSQNManager struct {
	ctrl     *gomock.Controller
	recorder *MockSQNManagerMockRecorder
	isgomock struct{}
}

// MockSQNManagerMockRecorder is the mock recorder for MockSQNManager.
type MockSQNManagerMockRecorder struct {
	mock *MockSQNManager
}

// NewMockSQNManager creates a new mock instance.
func NewMockSQNManager(ctrl *gomock.Controller) *MockSQNManager {
	mock := &MockSQNManager{ctrl: ctrl}
	mock.recorder = &MockSQNManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQNManager) EXPECT() *MockSQNManagerMockRecorder {
	return m.recorder
}

// FormatHex mocks base method.
func (m *MockSQNManager) FormatHex(sqn uint64) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatHex", sqn)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormatHex indicates an expected call of FormatHex.
func (mr *MockSQNManagerMockRecorder) FormatHex(sqn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatHex", reflect.TypeOf((*MockSQNManager)(nil).FormatHex), sqn)
}

// Increment mocks base method.
func (m *MockSQNManager) Increment(currentSQN uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Increment", currentSQN)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Increment indicates an expected call of Increment.
func (mr *MockSQNManagerMockRecorder) Increment(currentSQN any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Increment", reflect.TypeOf((*MockSQNManager)(nil).Increment), currentSQN)
}

// ParseHex mocks base method.
func (m *MockSQNManager) ParseHex(s string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseHex", s)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseHex indicates an expected call of ParseHex.
func (mr *MockSQNManagerMockRecorder) ParseHex(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseHex", reflect.TypeOf((*MockSQNManager)(nil).ParseHex), s)
}

// MockSQNValidator is a mock of SQNValidator interface.
type MockSQNValidator struct {
	ctrl     *gomock.Controller
	recorder *MockSQNValidatorMockRecorder
	isgomock struct{}
}

// MockSQNValidatorMockRecorder is the mock recorder for MockSQNValidator.
type MockSQNValidatorMockRecorder struct {
	mock *MockSQNValidator
}

// NewMockSQNValidator creates a new mock instance.
func NewMockSQNValidator(ctrl *gomock.Controller) *MockSQNValidator {
	mock := &MockSQNValidator{ctrl: ctrl}
	mock.recorder = &MockSQNValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQNValidator) EXPECT() *MockSQNValidatorMockRecorder {
	return m.recorder
}

// ComputeResyncSQN mocks base method.
func (m *MockSQNValidator) ComputeResyncSQN(sqnMS uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeResyncSQN", sqnMS)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComputeResyncSQN indicates an expected call of ComputeResyncSQN.
func (mr *MockSQNValidatorMockRecorder) ComputeResyncSQN(sqnMS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeResyncSQN", reflect.TypeOf((*MockSQNValidator)(nil).ComputeResyncSQN), sqnMS)
}

// ValidateResyncSQN mocks base method.
func (m *MockSQNValidator) ValidateResyncSQN(sqnMS, sqnHE uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateResyncSQN", sqnMS, sqnHE)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateResyncSQN indicates an expected call of ValidateResyncSQN.
func (mr *MockSQNValidatorMockRecorder) ValidateResyncSQN(sqnMS, sqnHE any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateResyncSQN", reflect.TypeOf((*MockSQNValidator)(nil).ValidateResyncSQN), sqnMS, sqnHE)
}

// MockSubscriberRepository is a mock of SubscriberRepository interface.
type MockSubscriberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriberRepositoryMockRecorder is the mock recorder for MockSubscriberRepository.
type MockSubscriberRepositoryMockRecorder struct {
	mock *MockSubscriberRepository
}

// NewMockSubscriberRepository creates a new mock instance.
func NewMockSubscriberRepository(ctrl *gomock.Controller) *MockSubscriberRepository {
	mock := &MockSubscriberRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriberRepository) EXPECT() *MockSubscriberRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSubscriberRepository) Get(ctx context.Context, imsi string) (*store.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, imsi)
	ret0, _ := ret[0].(*store.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSubscriberRepositoryMockRecorder) Get(ctx, imsi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSubscriberRepository)(nil).Get), ctx, imsi)
}

// UpdateSQN mocks base method.
func (m *MockSubscriberRepository) UpdateSQN(ctx context.Context, imsi, sqn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSQN", ctx, imsi, sqn)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSQN indicates an expected call of UpdateSQN.
func (mr *MockSubscriberRepositoryMockRecorder) UpdateSQN(ctx, imsi, sqn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSQN", reflect.TypeOf((*MockSubscriberRepository)(nil).UpdateSQN), ctx, imsi, sqn)
}

// MockTestVectorProvider is a mock of TestVectorProvider interface.
type MockTestVectorProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTestVectorProviderMockRecorder
	isgomock struct{}
}

// MockTestVectorProviderMockRecorder is the mock recorder for MockTestVectorProvider.
type MockTestVectorProviderMockRecorder struct {
	mock *MockTestVectorProvider
}

// NewMockTestVectorProvider creates a new mock instance.
func NewMockTestVectorProvider(ctrl *gomock.Controller) *MockTestVectorProvider {
	mock := &MockTestVectorProvider{ctrl: ctrl}
	mock.recorder = &MockTestVectorProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestVectorProvider) EXPECT() *MockTestVectorProviderMockRecorder {
	return m.recorder
}

// GetDefaultSQN mocks base method.
func (m *MockTestVectorProvider) GetDefaultSQN() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultSQN")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetDefaultSQN indicates an expected call of GetDefaultSQN.
func (mr *MockTestVectorProviderMockRecorder) GetDefaultSQN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultSQN", reflect.TypeOf((*MockTestVectorProvider)(nil).GetDefaultSQN))
}

// GetTestCryptoParams mocks base method.
func (m *MockTestVectorProvider) GetTestCryptoParams() ([]byte, []byte, []byte) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestCryptoParams")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].([]byte)
	return ret0, ret1, ret2
}

// GetTestCryptoParams indicates an expected call of GetTestCryptoParams.
func (mr *MockTestVectorProviderMockRecorder) GetTestCryptoParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestCryptoParams", reflect.TypeOf((*MockTestVectorProvider)(nil).GetTestCryptoParams))
}

// GetTestVector mocks base method.
func (m *MockTestVectorProvider) GetTestVector(imsi string) (*milenage.Vector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestVector", imsi)
	ret0, _ := ret[0].(*milenage.Vector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestVector indicates an expected call of GetTestVector.
func (mr *MockTestVectorProviderMockRecorder) GetTestVector(imsi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestVector", reflect.TypeOf((*MockTestVectorProvider)(nil).GetTestVector), imsi)
}

// IsTestIMSI mocks base method.
func (m *MockTestVectorProvider) IsTestIMSI(imsi string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTestIMSI", imsi)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTestIMSI indicates an expected call of IsTestIMSI.
func (mr *MockTestVectorProviderMockRecorder) IsTestIMSI(imsi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTestIMSI", reflect.TypeOf((*MockTestVectorProvider)(nil).IsTestIMSI), imsi)
}

// MockVectorUseCaseInterface is a mock of VectorUseCaseInterface interface.
type MockVectorUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockVectorUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockVectorUseCaseInterfaceMockRecorder is the mock recorder for MockVectorUseCaseInterface.
type MockVectorUseCaseInterfaceMockRecorder struct {
	mock *MockVectorUseCaseInterface
}

// NewMockVectorUseCaseInterface creates a new mock instance.
func NewMockVectorUseCaseInterface(ctrl *gomock.Controller) *MockVectorUseCaseInterface {
	mock := &MockVectorUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockVectorUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorUseCaseInterface) EXPECT() *MockVectorUseCaseInterfaceMockRecorder {
	return m.recorder
}

// GenerateVector mocks base method.
func (m *MockVectorUseCaseInterface) GenerateVector(ctx context.Context, req *dto.VectorRequest) (*dto.VectorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateVector", ctx, req)
	ret0, _ := ret[0].(*dto.VectorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateVector indicates an expected call of GenerateVector.
func (mr *MockVectorUseCaseInterfaceMockRecorder) GenerateVector(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateVector", reflect.TypeOf((*MockVectorUseCaseInterface)(nil).GenerateVector), ctx, req)
}
