// Code generated by MockGen. DO NOT EDIT.
// Source: internal/acct/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/acct/interfaces.go -destination=internal/mocks/acct_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	radius "github.com/oyaguma3/eapaka-radius-server-poc/apps/acct-server/internal/radius"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountingProcessor is a mock of AccountingProcessor interface.
type MockAccountingProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockAccountingProcessorMockRecorder
	isgomock struct{}
}

// MockAccountingProcessorMockRecorder is the mock recorder for MockAccountingProcessor.
type MockAccountingProcessorMockRecorder struct {
	mock *MockAccountingProcessor
}

// NewMockAccountingProcessor creates a new mock instance.
func NewMockAccountingProcessor(ctrl *gomock.Controller) *MockAccountingProcessor {
	mock := &MockAccountingProcessor{ctrl: ctrl}
	mock.recorder = &MockAccountingProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountingProcessor) EXPECT() *MockAccountingProcessorMockRecorder {
	return m.recorder
}

// ProcessInterim mocks base method.
func (m *MockAccountingProcessor) ProcessInterim(ctx context.Context, attrs *radius.AccountingAttributes, srcIP, traceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessInterim", ctx, attrs, srcIP, traceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessInterim indicates an expected call of ProcessInterim.
func (mr *MockAccountingProcessorMockRecorder) ProcessInterim(ctx, attrs, srcIP, traceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessInterim", reflect.TypeOf((*MockAccountingProcessor)(nil).ProcessInterim), ctx, attrs, srcIP, traceID)
}

// ProcessStart mocks base method.
func (m *MockAccountingProcessor) ProcessStart(ctx context.Context, attrs *radius.AccountingAttributes, srcIP, traceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessStart", ctx, attrs, srcIP, traceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessStart indicates an expected call of ProcessStart.
func (mr *MockAccountingProcessorMockRecorder) ProcessStart(ctx, attrs, srcIP, traceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessStart", reflect.TypeOf((*MockAccountingProcessor)(nil).ProcessStart), ctx, attrs, srcIP, traceID)
}

// ProcessStop mocks base method.
func (m *MockAccountingProcessor) ProcessStop(ctx context.Context, attrs *radius.AccountingAttributes, srcIP, traceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessStop", ctx, attrs, srcIP, traceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessStop indicates an expected call of ProcessStop.
func (mr *MockAccountingProcessorMockRecorder) ProcessStop(ctx, attrs, srcIP, traceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessStop", reflect.TypeOf((*MockAccountingProcessor)(nil).ProcessStop), ctx, attrs, srcIP, traceID)
}

// MockDuplicateDetector is a mock of DuplicateDetector interface.
type MockDuplicateDetector struct {
	ctrl     *gomock.Controller
	recorder *MockDuplicateDetectorMockRecorder
	isgomock struct{}
}

// MockDuplicateDetectorMockRecorder is the mock recorder for MockDuplicateDetector.
type MockDuplicateDetectorMockRecorder struct {
	mock *MockDuplicateDetector
}

// NewMockDuplicateDetector creates a new mock instance.
func NewMockDuplicateDetector(ctrl *gomock.Controller) *MockDuplicateDetector {
	mock := &MockDuplicateDetector{ctrl: ctrl}
	mock.recorder = &MockDuplicateDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDuplicateDetector) EXPECT() *MockDuplicateDetectorMockRecorder {
	return m.recorder
}

// CheckAndMarkStart mocks base method.
func (m *MockDuplicateDetector) CheckAndMarkStart(ctx context.Context, acctSessionID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAndMarkStart", ctx, acctSessionID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAndMarkStart indicates an expected call of CheckAndMarkStart.
func (mr *MockDuplicateDetectorMockRecorder) CheckAndMarkStart(ctx, acctSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAndMarkStart", reflect.TypeOf((*MockDuplicateDetector)(nil).CheckAndMarkStart), ctx, acctSessionID)
}

// CheckInterimDuplicate mocks base method.
func (m *MockDuplicateDetector) CheckInterimDuplicate(ctx context.Context, acctSessionID string, input, output uint32) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInterimDuplicate", ctx, acctSessionID, input, output)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckInterimDuplicate indicates an expected call of CheckInterimDuplicate.
func (mr *MockDuplicateDetectorMockRecorder) CheckInterimDuplicate(ctx, acctSessionID, input, output any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInterimDuplicate", reflect.TypeOf((*MockDuplicateDetector)(nil).CheckInterimDuplicate), ctx, acctSessionID, input, output)
}

// CheckStopDuplicate mocks base method.
func (m *MockDuplicateDetector) CheckStopDuplicate(ctx context.Context, acctSessionID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStopDuplicate", ctx, acctSessionID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckStopDuplicate indicates an expected call of CheckStopDuplicate.
func (mr *MockDuplicateDetectorMockRecorder) CheckStopDuplicate(ctx, acctSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStopDuplicate", reflect.TypeOf((*MockDuplicateDetector)(nil).CheckStopDuplicate), ctx, acctSessionID)
}

// HasSeenStart mocks base method.
func (m *MockDuplicateDetector) HasSeenStart(ctx context.Context, acctSessionID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSeenStart", ctx, acctSessionID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasSeenStart indicates an expected call of HasSeenStart.
func (mr *MockDuplicateDetectorMockRecorder) HasSeenStart(ctx, acctSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSeenStart", reflect.TypeOf((*MockDuplicateDetector)(nil).HasSeenStart), ctx, acctSessionID)
}

// MarkAsStart mocks base method.
func (m *MockDuplicateDetector) MarkAsStart(ctx context.Context, acctSessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsStart", ctx, acctSessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsStart indicates an expected call of MarkAsStart.
func (mr *MockDuplicateDetectorMockRecorder) MarkAsStart(ctx, acctSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsStart", reflect.TypeOf((*MockDuplicateDetector)(nil).MarkAsStart), ctx, acctSessionID)
}

// MarkAsStopped mocks base method.
func (m *MockDuplicateDetector) MarkAsStopped(ctx context.Context, acctSessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsStopped", ctx, acctSessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsStopped indicates an expected call of MarkAsStopped.
func (mr *MockDuplicateDetectorMockRecorder) MarkAsStopped(ctx, acctSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsStopped", reflect.TypeOf((*MockDuplicateDetector)(nil).MarkAsStopped), ctx, acctSessionID)
}
