// Code generated by MockGen. DO NOT EDIT.
// Source: internal/session/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/session/interfaces.go -destination=internal/mocks/session_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	session "github.com/oyaguma3/eapaka-radius-server-poc/apps/acct-server/internal/session"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionManager) Delete(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionManagerMockRecorder) Delete(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionManager)(nil).Delete), ctx, uuid)
}

// Exists mocks base method.
func (m *MockSessionManager) Exists(ctx context.Context, uuid string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, uuid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockSessionManagerMockRecorder) Exists(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockSessionManager)(nil).Exists), ctx, uuid)
}

// Get mocks base method.
func (m *MockSessionManager) Get(ctx context.Context, uuid string) (*session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionManagerMockRecorder) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionManager)(nil).Get), ctx, uuid)
}

// RemoveUserIndex mocks base method.
func (m *MockSessionManager) RemoveUserIndex(ctx context.Context, imsi, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserIndex", ctx, imsi, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserIndex indicates an expected call of RemoveUserIndex.
func (mr *MockSessionManagerMockRecorder) RemoveUserIndex(ctx, imsi, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserIndex", reflect.TypeOf((*MockSessionManager)(nil).RemoveUserIndex), ctx, imsi, uuid)
}

// UpdateOnInterim mocks base method.
func (m *MockSessionManager) UpdateOnInterim(ctx context.Context, uuid string, data *session.SessionInterimData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOnInterim", ctx, uuid, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOnInterim indicates an expected call of UpdateOnInterim.
func (mr *MockSessionManagerMockRecorder) UpdateOnInterim(ctx, uuid, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOnInterim", reflect.TypeOf((*MockSessionManager)(nil).UpdateOnInterim), ctx, uuid, data)
}

// UpdateOnStart mocks base method.
func (m *MockSessionManager) UpdateOnStart(ctx context.Context, uuid string, data *session.SessionStartData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOnStart", ctx, uuid, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOnStart indicates an expected call of UpdateOnStart.
func (mr *MockSessionManagerMockRecorder) UpdateOnStart(ctx, uuid, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOnStart", reflect.TypeOf((*MockSessionManager)(nil).UpdateOnStart), ctx, uuid, data)
}

// MockIdentifierResolver is a mock of IdentifierResolver interface.
type MockIdentifierResolver struct {
	ctrl     *gomock.Controller
	recorder *MockIdentifierResolverMockRecorder
	isgomock struct{}
}

// MockIdentifierResolverMockRecorder is the mock recorder for MockIdentifierResolver.
type MockIdentifierResolverMockRecorder struct {
	mock *MockIdentifierResolver
}

// NewMockIdentifierResolver creates a new mock instance.
func NewMockIdentifierResolver(ctrl *gomock.Controller) *MockIdentifierResolver {
	mock := &MockIdentifierResolver{ctrl: ctrl}
	mock.recorder = &MockIdentifierResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentifierResolver) EXPECT() *MockIdentifierResolverMockRecorder {
	return m.recorder
}

// ResolveIMSI mocks base method.
func (m *MockIdentifierResolver) ResolveIMSI(ctx context.Context, sessionUUID, userName, classUUID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveIMSI", ctx, sessionUUID, userName, classUUID)
	ret0, _ := ret[0].(string)
	return ret0
}

// ResolveIMSI indicates an expected call of ResolveIMSI.
func (mr *MockIdentifierResolverMockRecorder) ResolveIMSI(ctx, sessionUUID, userName, classUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveIMSI", reflect.TypeOf((*MockIdentifierResolver)(nil).ResolveIMSI), ctx, sessionUUID, userName, classUUID)
}
