// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/store/interfaces.go -destination=internal/mocks/store_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClientStore is a mock of ClientStore interface.
type MockClientStore struct {
	ctrl     *gomock.Controller
	recorder *MockClientStoreMockRecorder
	isgomock struct{}
}

// MockClientStoreMockRecorder is the mock recorder for MockClientStore.
type MockClientStoreMockRecorder struct {
	mock *MockClientStore
}

// NewMockClientStore creates a new mock instance.
func NewMockClientStore(ctrl *gomock.Controller) *MockClientStore {
	mock := &MockClientStore{ctrl: ctrl}
	mock.recorder = &MockClientStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientStore) EXPECT() *MockClientStoreMockRecorder {
	return m.recorder
}

// GetClientSecret mocks base method.
func (m *MockClientStore) GetClientSecret(ctx context.Context, ip string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientSecret", ctx, ip)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientSecret indicates an expected call of GetClientSecret.
func (mr *MockClientStoreMockRecorder) GetClientSecret(ctx, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientSecret", reflect.TypeOf((*MockClientStore)(nil).GetClientSecret), ctx, ip)
}

// MockSessionStore is a mock of SessionStore interface.
type MockSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreMockRecorder
	isgomock struct{}
}

// MockSessionStoreMockRecorder is the mock recorder for MockSessionStore.
type MockSessionStoreMockRecorder struct {
	mock *MockSessionStore
}

// NewMockSessionStore creates a new mock instance.
func NewMockSessionStore(ctrl *gomock.Controller) *MockSessionStore {
	mock := &MockSessionStore{ctrl: ctrl}
	mock.recorder = &MockSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStore) EXPECT() *MockSessionStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionStore) Delete(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionStoreMockRecorder) Delete(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionStore)(nil).Delete), ctx, uuid)
}

// Exists mocks base method.
func (m *MockSessionStore) Exists(ctx context.Context, uuid string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, uuid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockSessionStoreMockRecorder) Exists(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockSessionStore)(nil).Exists), ctx, uuid)
}

// Get mocks base method.
func (m *MockSessionStore) Get(ctx context.Context, uuid string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionStoreMockRecorder) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionStore)(nil).Get), ctx, uuid)
}

// RemoveUserIndex mocks base method.
func (m *MockSessionStore) RemoveUserIndex(ctx context.Context, imsi, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserIndex", ctx, imsi, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserIndex indicates an expected call of RemoveUserIndex.
func (mr *MockSessionStoreMockRecorder) RemoveUserIndex(ctx, imsi, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserIndex", reflect.TypeOf((*MockSessionStore)(nil).RemoveUserIndex), ctx, imsi, uuid)
}

// UpdateOnInterim mocks base method.
func (m *MockSessionStore) UpdateOnInterim(ctx context.Context, uuid string, fields map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOnInterim", ctx, uuid, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOnInterim indicates an expected call of UpdateOnInterim.
func (mr *MockSessionStoreMockRecorder) UpdateOnInterim(ctx, uuid, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOnInterim", reflect.TypeOf((*MockSessionStore)(nil).UpdateOnInterim), ctx, uuid, fields)
}

// UpdateOnStart mocks base method.
func (m *MockSessionStore) UpdateOnStart(ctx context.Context, uuid string, fields map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOnStart", ctx, uuid, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOnStart indicates an expected call of UpdateOnStart.
func (mr *MockSessionStoreMockRecorder) UpdateOnStart(ctx, uuid, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOnStart", reflect.TypeOf((*MockSessionStore)(nil).UpdateOnStart), ctx, uuid, fields)
}

// MockDuplicateStore is a mock of DuplicateStore interface.
type MockDuplicateStore struct {
	ctrl     *gomock.Controller
	recorder *MockDuplicateStoreMockRecorder
	isgomock struct{}
}

// MockDuplicateStoreMockRecorder is the mock recorder for MockDuplicateStore.
type MockDuplicateStoreMockRecorder struct {
	mock *MockDuplicateStore
}

// NewMockDuplicateStore creates a new mock instance.
func NewMockDuplicateStore(ctrl *gomock.Controller) *MockDuplicateStore {
	mock := &MockDuplicateStore{ctrl: ctrl}
	mock.recorder = &MockDuplicateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDuplicateStore) EXPECT() *MockDuplicateStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDuplicateStore) Get(ctx context.Context, acctSessionID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, acctSessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDuplicateStoreMockRecorder) Get(ctx, acctSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDuplicateStore)(nil).Get), ctx, acctSessionID)
}

// Set mocks base method.
func (m *MockDuplicateStore) Set(ctx context.Context, acctSessionID, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, acctSessionID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockDuplicateStoreMockRecorder) Set(ctx, acctSessionID, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockDuplicateStore)(nil).Set), ctx, acctSessionID, value)
}
