// Code generated by MockGen. DO NOT EDIT.
// Source: internal/eap/types.go
//
// Generated by this command:
//
//	mockgen -source=internal/eap/types.go -destination=internal/mocks/eap_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	eap "github.com/oyaguma3/eapaka-radius-server-poc/apps/auth-server/internal/eap"
	gomock "go.uber.org/mock/gomock"
)

// MockEAPProcessor is a mock of EAPProcessor interface.
type MockEAPProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockEAPProcessorMockRecorder
	isgomock struct{}
}

// MockEAPProcessorMockRecorder is the mock recorder for MockEAPProcessor.
type MockEAPProcessorMockRecorder struct {
	mock *MockEAPProcessor
}

// NewMockEAPProcessor creates a new mock instance.
func NewMockEAPProcessor(ctrl *gomock.Controller) *MockEAPProcessor {
	mock := &MockEAPProcessor{ctrl: ctrl}
	mock.recorder = &MockEAPProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEAPProcessor) EXPECT() *MockEAPProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockEAPProcessor) Process(ctx context.Context, req *eap.Request) (*eap.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, req)
	ret0, _ := ret[0].(*eap.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockEAPProcessorMockRecorder) Process(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockEAPProcessor)(nil).Process), ctx, req)
}
