// Code generated by MockGen. DO NOT EDIT.
// Source: internal/policy/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/policy/interfaces.go -destination=internal/mocks/policy_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	policy "github.com/oyaguma3/eapaka-radius-server-poc/apps/auth-server/internal/policy"
	gomock "go.uber.org/mock/gomock"
)

// MockPolicyStore is a mock of PolicyStore interface.
type MockPolicyStore struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyStoreMockRecorder
	isgomock struct{}
}

// MockPolicyStoreMockRecorder is the mock recorder for MockPolicyStore.
type MockPolicyStoreMockRecorder struct {
	mock *MockPolicyStore
}

// NewMockPolicyStore creates a new mock instance.
func NewMockPolicyStore(ctrl *gomock.Controller) *MockPolicyStore {
	mock := &MockPolicyStore{ctrl: ctrl}
	mock.recorder = &MockPolicyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyStore) EXPECT() *MockPolicyStoreMockRecorder {
	return m.recorder
}

// GetPolicy mocks base method.
func (m *MockPolicyStore) GetPolicy(ctx context.Context, imsi string) (*policy.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy", ctx, imsi)
	ret0, _ := ret[0].(*policy.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockPolicyStoreMockRecorder) GetPolicy(ctx, imsi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockPolicyStore)(nil).GetPolicy), ctx, imsi)
}

// MockEvaluator is a mock of Evaluator interface.
type MockEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockEvaluatorMockRecorder
	isgomock struct{}
}

// MockEvaluatorMockRecorder is the mock recorder for MockEvaluator.
type MockEvaluatorMockRecorder struct {
	mock *MockEvaluator
}

// NewMockEvaluator creates a new mock instance.
func NewMockEvaluator(ctrl *gomock.Controller) *MockEvaluator {
	mock := &MockEvaluator{ctrl: ctrl}
	mock.recorder = &MockEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvaluator) EXPECT() *MockEvaluatorMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockEvaluator) Evaluate(arg0 *policy.Policy, nasID, ssid string) *policy.EvaluationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", arg0, nasID, ssid)
	ret0, _ := ret[0].(*policy.EvaluationResult)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockEvaluatorMockRecorder) Evaluate(arg0, nasID, ssid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockEvaluator)(nil).Evaluate), arg0, nasID, ssid)
}
