// Code generated by MockGen. DO NOT EDIT.
// Source: internal/session/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/session/interfaces.go -destination=internal/mocks/session_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	session "github.com/oyaguma3/eapaka-radius-server-poc/apps/auth-server/internal/session"
	gomock "go.uber.org/mock/gomock"
)

// MockContextStore is a mock of ContextStore interface.
type MockContextStore struct {
	ctrl     *gomock.Controller
	recorder *MockContextStoreMockRecorder
	isgomock struct{}
}

// MockContextStoreMockRecorder is the mock recorder for MockContextStore.
type MockContextStoreMockRecorder struct {
	mock *MockContextStore
}

// NewMockContextStore creates a new mock instance.
func NewMockContextStore(ctrl *gomock.Controller) *MockContextStore {
	mock := &MockContextStore{ctrl: ctrl}
	mock.recorder = &MockContextStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextStore) EXPECT() *MockContextStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockContextStore) Create(ctx context.Context, traceID string, eapCtx *session.EAPContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, traceID, eapCtx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockContextStoreMockRecorder) Create(ctx, traceID, eapCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContextStore)(nil).Create), ctx, traceID, eapCtx)
}

// Delete mocks base method.
func (m *MockContextStore) Delete(ctx context.Context, traceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, traceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockContextStoreMockRecorder) Delete(ctx, traceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContextStore)(nil).Delete), ctx, traceID)
}

// Exists mocks base method.
func (m *MockContextStore) Exists(ctx context.Context, traceID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, traceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockContextStoreMockRecorder) Exists(ctx, traceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockContextStore)(nil).Exists), ctx, traceID)
}

// Get mocks base method.
func (m *MockContextStore) Get(ctx context.Context, traceID string) (*session.EAPContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, traceID)
	ret0, _ := ret[0].(*session.EAPContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockContextStoreMockRecorder) Get(ctx, traceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContextStore)(nil).Get), ctx, traceID)
}

// Update mocks base method.
func (m *MockContextStore) Update(ctx context.Context, traceID string, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, traceID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockContextStoreMockRecorder) Update(ctx, traceID, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContextStore)(nil).Update), ctx, traceID, updates)
}

// MockSessionStore is a mock of SessionStore interface.
type MockSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreMockRecorder
	isgomock struct{}
}

// MockSessionStoreMockRecorder is the mock recorder for MockSessionStore.
type MockSessionStoreMockRecorder struct {
	mock *MockSessionStore
}

// NewMockSessionStore creates a new mock instance.
func NewMockSessionStore(ctrl *gomock.Controller) *MockSessionStore {
	mock := &MockSessionStore{ctrl: ctrl}
	mock.recorder = &MockSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStore) EXPECT() *MockSessionStoreMockRecorder {
	return m.recorder
}

// AddUserIndex mocks base method.
func (m *MockSessionStore) AddUserIndex(ctx context.Context, imsi, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserIndex", ctx, imsi, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserIndex indicates an expected call of AddUserIndex.
func (mr *MockSessionStoreMockRecorder) AddUserIndex(ctx, imsi, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserIndex", reflect.TypeOf((*MockSessionStore)(nil).AddUserIndex), ctx, imsi, sessionID)
}

// Create mocks base method.
func (m *MockSessionStore) Create(ctx context.Context, sessionID string, sess *session.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, sessionID, sess)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionStoreMockRecorder) Create(ctx, sessionID, sess any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionStore)(nil).Create), ctx, sessionID, sess)
}

// Get mocks base method.
func (m *MockSessionStore) Get(ctx context.Context, sessionID string) (*session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, sessionID)
	ret0, _ := ret[0].(*session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionStoreMockRecorder) Get(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionStore)(nil).Get), ctx, sessionID)
}
