// Code generated by MockGen. DO NOT EDIT.
// Source: internal/vector/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/vector/interfaces.go -destination=internal/mocks/vector_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vector "github.com/oyaguma3/eapaka-radius-server-poc/apps/auth-server/internal/vector"
	gomock "go.uber.org/mock/gomock"
)

// MockVectorClient is a mock of VectorClient interface.
type MockVectorClient struct {
	ctrl     *gomock.Controller
	recorder *MockVectorClientMockRecorder
	isgomock struct{}
}

// MockVectorClientMockRecorder is the mock recorder for MockVectorClient.
type MockVectorClientMockRecorder struct {
	mock *MockVectorClient
}

// NewMockVectorClient creates a new mock instance.
func NewMockVectorClient(ctrl *gomock.Controller) *MockVectorClient {
	mock := &MockVectorClient{ctrl: ctrl}
	mock.recorder = &MockVectorClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorClient) EXPECT() *MockVectorClientMockRecorder {
	return m.recorder
}

// GetVector mocks base method.
func (m *MockVectorClient) GetVector(ctx context.Context, req *vector.VectorRequest) (*vector.VectorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVector", ctx, req)
	ret0, _ := ret[0].(*vector.VectorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVector indicates an expected call of GetVector.
func (mr *MockVectorClientMockRecorder) GetVector(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVector", reflect.TypeOf((*MockVectorClient)(nil).GetVector), ctx, req)
}
